<?php

namespace ProcessMaker\Package\Connectors\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use ProcessMaker\Package\Connectors\Enums\StatusEnum;
use ProcessMaker\Package\Connectors\Models\Sample;

class SampleModelFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return string
     */
    public function modelName()
    {
        return Sample::class;
    }

    /**
     * {@inheritdoc}
     */
    public function definition()
    {
        return [
            'name' => $this->faker->name(),
            'status' => $this->faker->randomElement([
                StatusEnum::ENABLED,
                StatusEnum::DISABLED,
            ]),
        ];
    }
}
